// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3jVufup_rcrgoDsu-GPTIjFs-VDpLwSE',
    appId: '1:541082437341:web:3f308fa5b916f148807d34',
    messagingSenderId: '541082437341',
    projectId: 'devpara',
    authDomain: 'devpara.firebaseapp.com',
    storageBucket: 'devpara.appspot.com',
    measurementId: 'G-SK9PG9PJ8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWghUvYQOsZSDIhm_GtroUcx6LJklT578',
    appId: '1:541082437341:android:a546c3c8a7379c69807d34',
    messagingSenderId: '541082437341',
    projectId: 'devpara',
    storageBucket: 'devpara.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNEvJ-8vQum-pCUxidvus3csXvR4sxw9g',
    appId: '1:541082437341:ios:7b624bd3e30b03a6807d34',
    messagingSenderId: '541082437341',
    projectId: 'devpara',
    storageBucket: 'devpara.appspot.com',
    iosClientId: '541082437341-nd440odgimvrm3mscp04164g2fd420ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.devpara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNEvJ-8vQum-pCUxidvus3csXvR4sxw9g',
    appId: '1:541082437341:ios:7b624bd3e30b03a6807d34',
    messagingSenderId: '541082437341',
    projectId: 'devpara',
    storageBucket: 'devpara.appspot.com',
    iosClientId: '541082437341-nd440odgimvrm3mscp04164g2fd420ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.devpara',
  );
}
